/**
 * SELECT * FROM V$PARAMETER WHERE NAME LIKE '%job%';
 * ALTER SYSTEM SET JOB_QUEUE_PROCESSES = 1000;
 */

VARIABLE JOB_NUMBER NUMBER;
BEGIN
    SYS.DBMS_JOB.SUBMIT(:JOB_NUMBER, 'gpms.PRC_JOB_PREDCT;', TO_DATE('20170919010000','YYYYMMDDHH24MISS'),'TRUNC(LAST_DAY(SYSDATE))+1+1/24'); -- 매월 1일 새벽 1시
END;