/*
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
    https://github.com/geops/ole/blob/master/license.txt
 @link       https://github.com/geops/ole
*/
OpenLayers.Lang.en=OpenLayers.Util.extend(OpenLayers.Lang.en,{oleCleanFeature:"Clean selected geometry",oleDeleteFeature:"Delete selected geometry",oleDeleteAllFeatures:"Delete all geometries",oleDownloadFeature:"Download geometries",oleDownloadFeatureEmpty:"No geometries to download",oleDownloadFeatureFileFormat:"Select a file format",oleUploadFeature:"Upload geometries from local file",oleUploadFeatureNoFile:"No file specified. Please choose a file and try again.",oleUploadFeatureNone:"No or unreadable geometries found in file",
oleDragFeature:"Drag geometry",oleDrawHole:"Draw hole",oleDrawPolygon:"Draw polygon",oleDrawPath:"Draw path",oleDrawPoint:"Draw point",oleDrawText:"Draw text label",oleDrawTextEdit:"Add label text in box,<br>then press enter or close popup",oleDrawRegular:"Draw regular polygon",oleDrawRegularShape:"Shape",oleDrawRegularIrregular:"Irregular",oleDrawRegularSides3:"triangle",oleDrawRegularSides4:"square",oleDrawRegularSides5:"pentagon",oleDrawRegularSides6:"hexagon",oleDrawRegularCircle:"circle",oleImportFeature:"Import selected geometry",
oleImportFeatureSourceLayer:"Found no source layer.",oleImportFeatureSourceFeature:"Please select a geometry first.",oleLayerSettingsImportHeader:"Import",oleLayerSettingsImportLabel:"Use as source layer",oleLayerSettingsLegendHeader:"Legend",oleLayerSettingsOpacityHeader:"Opacity (%)",oleMergeFeature:"Merge selected geometry",oleMergeFeatureSelectFeature:"Please select at least 2 geometries.",oleModifyFeature:"Modify geometry",oleNavigation:"Navigation",olePixelUnit:"px",oleSelectFeature:"Select geometry",
oleSnappingSettings:"Snapping settings",oleSnappingSettingsLayer:"Snapping layer",oleSnappingSettingsTolerance:"Snapping tolerance",oleSplitFeature:"Split selected geometry",oleTransformFeature:"Scale, rotate and move geometry",oleCADTools:"CAD Tools",oleCADToolsDialogParallelDrawing:"Parallel Drawing",oleCADToolsDialogGuidedDrawing:"Guided Drawing",oleCADToolsDialogShowLayer:"Show Guide Lines",oleCADToolsDialogTolerance:"px tolerance",oleDialogCancelButton:"Cancel",oleDialogSaveButton:"Save",oleDialogOkButton:"Okay"});
OpenLayers.Editor=OpenLayers.Class({map:null,id:null,editLayer:null,editorPanel:null,editMode:false,dialog:null,showStatus:function(a,b){a==="error"&&alert(b)},activeControls:[],editorControls:["CleanFeature","DeleteFeature","DeleteAllFeatures","Dialog","DrawHole","DrawRegular","DrawPolygon","DrawPath","DrawPoint","DrawText","EditorPanel","ImportFeature","MergeFeature","SnappingSettings","SplitFeature","CADTools","TransformFeature"],featureTypes:["text","point","path","polygon","regular"],sourceLayers:[],
params:{},geoJSON:new OpenLayers.Format.GeoJSON,options:{},oleUrl:"",controls:{},undoRedoActive:true,initialize:function(a,b){OpenLayers.Util.extend(this,b);this.map=a instanceof OpenLayers.Map?a:new OpenLayers.Map;b||(b={});if(!b.dialog){this.dialog=new OpenLayers.Editor.Control.Dialog;this.map.addControl(this.dialog)}this.id=OpenLayers.Util.createUniqueID("OpenLayers.Editor_");this.editLayer=b.editLayer?b.editLayer:new OpenLayers.Layer.Vector("Editor",{displayInLayerSwitcher:false});this.editLayer.styleMap=
b.styleMap?b.styleMap:new OpenLayers.StyleMap({"default":new OpenLayers.Style({fillColor:"#07f",fillOpacity:0.8,strokeColor:"#037",strokeWidth:2,graphicZIndex:1,pointRadius:5}),defaultLabel:new OpenLayers.Style({fillColor:"#07f",fillOpacity:0.8,strokeColor:"#037",strokeWidth:2,graphicZIndex:11,pointRadius:0,cursor:"default",label:"${label}",fontColor:"#000000",fontSize:"11px",fontFamily:"Verdana, Arial, Helvetica, sans-serif",fontWeight:"bold",labelOutlineColor:"#FFFFFF",labelOutlineWidth:4,labelSelect:true}),
select:new OpenLayers.Style({fillColor:"#fc0",strokeColor:"#f70",graphicZIndex:2}),selectLabel:new OpenLayers.Style({pointRadius:5,label:"${label}",fontColor:"black",fontSize:"11px",fontFamily:"Verdana, Arial, Helvetica, sans-serif",fontWeight:"bold",labelAlign:"cm",labelXOffset:"${xOffset}",labelYOffset:"${yOffset}",fillColor:"#fc0",strokeColor:"#f70",labelOutlineColor:"#fc0",labelOutlineWidth:6,graphicZIndex:2}),temporary:new OpenLayers.Style({fillColor:"#fc0",fillOpacity:0.8,strokeColor:"#f70",
strokeWidth:2,graphicZIndex:2,pointRadius:5})});var c={editor:this,layer:this.editLayer,controls:["OpenLayers.Editor.Control.DeleteFeature","OpenLayers.Editor.Control.CleanFeature","OpenLayers.Editor.Control.MergeFeature","OpenLayers.Editor.Control.SplitFeature"]};this.editLayer.events.register("featureselected",c,this.selectionChanged);this.editLayer.events.register("featureunselected",c,this.selectionChanged);for(var d=0,e=this.featureTypes.length;d<e;d++)if(this.featureTypes[d]=="polygon")this.activeControls.push("DrawPolygon");
else if(this.featureTypes[d]=="path")this.activeControls.push("DrawPath");else if(this.featureTypes[d]=="point")this.activeControls.push("DrawPoint");else if(this.featureTypes[d]=="regular")this.activeControls.push("DrawRegular");else this.featureTypes[d]=="text"&&this.activeControls.push("DrawText");d=0;for(e=this.sourceLayers.length;d<e;d++){c={editor:this,layer:this.sourceLayers[d],controls:["OpenLayers.Editor.Control.ImportFeature"]};this.sourceLayers[d].events.register("featureselected",c,this.selectionChanged);
this.sourceLayers[d].events.register("featureunselected",c,this.selectionChanged);this.sourceLayers[d].styleMap=new OpenLayers.StyleMap({"default":new OpenLayers.Style({fillColor:"#0c0",fillOpacity:0.8,strokeColor:"#070",strokeWidth:2,graphicZIndex:1,pointRadius:5}),select:new OpenLayers.Style({fillColor:"#fc0",strokeColor:"#f70",graphicZIndex:2}),temporary:new OpenLayers.Style({fillColor:"#fc0",fillOpacity:0.8,strokeColor:"#f70",strokeWidth:2,graphicZIndex:2,pointRadius:5})});this.map.addLayer(this.sourceLayers[d])}this.map.editor=
this;this.map.addLayer(this.editLayer);this.map.addControl(new OpenLayers.Editor.Control.LayerSettings(this));this.undoRedoActive&&this.map.addControl(new OpenLayers.Editor.Control.UndoRedo(this.editLayer));this.addEditorControls();return this},selectionChanged:function(){var a=this.editor.editorPanel.getControlsByClass("OpenLayers.Control.SelectFeature")[0];if(this.layer.selectedFeatures.length>0&&a&&a.active){a=0;for(var b=this.controls.length;a<b;a++){var c=this.editor.editorPanel.getControlsByClass(this.controls[a])[0];
c&&OpenLayers.Element.removeClass(c.panel_div,"oleControlDisabled")}}else{a=0;for(b=this.controls.length;a<b;a++)(c=this.editor.editorPanel.getControlsByClass(this.controls[a])[0])&&OpenLayers.Element.addClass(c.panel_div,"oleControlDisabled")}this.editor.editorPanel.redraw()},startEditMode:function(){this.editMode=true;this.editorPanel.activate()},stopEditMode:function(){this.editMode=false;this.editorPanel.deactivate()},addEditorControls:function(){for(var a=null,b=[],c=0,d=this.activeControls.length;c<
d;c++){a=this.activeControls[c];OpenLayers.Util.indexOf(this.editorControls,a)>-1&&b.push(new OpenLayers.Editor.Control[a](this.editLayer,this.options[a]));switch(a){case "Separator":b.push(new OpenLayers.Control.Button({displayClass:"olControlSeparator"}));break;case "Navigation":b.push(new OpenLayers.Control.Navigation(OpenLayers.Util.extend({title:OpenLayers.i18n("oleNavigation")},this.options.Navigation)));break;case "DragFeature":b.push(new OpenLayers.Editor.Control.DragFeature(this.editLayer,
OpenLayers.Util.extend({},this.options.DragFeature)));break;case "ModifyFeature":b.push(new OpenLayers.Control.ModifyFeature(this.editLayer,OpenLayers.Util.extend({title:OpenLayers.i18n("oleModifyFeature")},this.options.ModifyFeature)));break;case "SelectFeature":b.push(new OpenLayers.Control.SelectFeature(this.sourceLayers.concat([this.editLayer]),OpenLayers.Util.extend({title:OpenLayers.i18n("oleSelectFeature"),clickout:true,toggle:false,multiple:false,hover:false,toggleKey:"ctrlKey",multipleKey:"ctrlKey",
box:true},this.options.SelectFeature)));break;case "DownloadFeature":b.push(new OpenLayers.Editor.Control.DownloadFeature(this.editLayer,OpenLayers.Util.extend({},this.DownloadFeature)));break;case "UploadFeature":b.push(new OpenLayers.Editor.Control.UploadFeature(this.editLayer,OpenLayers.Util.extend({},this.UploadFeature)))}this.controls[a]=b[b.length-1]}this.editorPanel=this.createEditorPanel(b);this.map.addControl(this.editorPanel)},addEditorControl:function(a){this.controls[a.CLASS_NAME]=a;this.editorPanel.addControls([a]);
this.map.addControl(a)},createEditorPanel:function(a){var b=new OpenLayers.Editor.Control.EditorPanel(this);b.addControls(a);return b},status:function(a){a.type=="error"&&alert(a.content)},loadFeatures:function(a){this.editLayer.destroyFeatures();if(a){this.editLayer.addFeatures(a);this.map.zoomToExtent(this.editLayer.getDataExtent())}},requestComplete:function(a){a=(new OpenLayers.Format.JSON).read(a.responseText);this.map.editor.stopWaiting();if(a)if(a.error)this.showStatus("error",a.message);else{a.params&&
OpenLayers.Util.extend(this.params,a.params);if(a.geo){a=this.geoJSON.read(a.geo);this.editLayer.removeFeatures(this.editLayer.selectedFeatures);this.editLayer.addFeatures(this.toFeatures(a));this.editLayer.events.triggerEvent("featureselected")}}else this.showStatus("error",OpenLayers.i18n("oleNoJSON"))},toFeatures:function(a){if(a===null||typeof a!=="object")throw Error("Parameter does not match expected type.");var b=[];a instanceof Array||(a=[a]);for(var c=0,d=a.length;c<d;c++)if(a[c].geometry.CLASS_NAME===
"OpenLayers.Geometry.MultiPolygon"||a[c].geometry.CLASS_NAME==="OpenLayers.Geometry.Collection")for(var e=0,f=a[c].geometry.components.length;e<f;e++)b.push(new OpenLayers.Feature.Vector(a[c].geometry.components[e]));else a[c].geometry.CLASS_NAME==="OpenLayers.Geometry.Polygon"&&b.push(new OpenLayers.Feature.Vector(a[c].geometry));return b},toMultiPolygon:function(a){for(var b=[],c=0,d=a.length;c<d;c++)a[c].geometry.CLASS_NAME==="OpenLayers.Geometry.Polygon"&&b.push(a[c].geometry);return new OpenLayers.Geometry.MultiPolygon(b)},
startWaiting:function(a){OpenLayers.Element.addClass(a,"olEditorWaiting");OpenLayers.Element.addClass(this.map.div,"olEditorWaiting");this.waitingDiv=a},stopWaiting:function(){OpenLayers.Element.removeClass(this.waitingDiv,"olEditorWaiting");OpenLayers.Element.removeClass(this.map.div,"olEditorWaiting")},CLASS_NAME:"OpenLayers.Editor"});OpenLayers.Editor.Control=OpenLayers.Class(OpenLayers.Control,{initialize:function(a){OpenLayers.Control.prototype.initialize.apply(this,[a])},CLASS_NAME:"OpenLayers.Editor.Control"});
OpenLayers.Editor.VERSION_NUMBER="1.0-beta1";
OpenLayers.Editor.Control.CleanFeature=OpenLayers.Class(OpenLayers.Control.Button,{proxy:null,title:OpenLayers.i18n("oleCleanFeature"),initialize:function(a,b){this.layer=a;OpenLayers.Control.Button.prototype.initialize.apply(this,[b]);this.trigger=this.cleanFeature;this.title=OpenLayers.i18n("oleCleanFeature");this.displayClass="oleControlDisabled "+this.displayClass},cleanFeature:function(){if(this.layer.selectedFeatures.length>0){var a=(new OpenLayers.Format.WKT).write(this.layer.selectedFeatures);this.map.editor.startWaiting(this.panel_div);
OpenLayers.Request.POST({url:this.map.editor.oleUrl+"process/clean",data:OpenLayers.Util.getParameterString({geo:a}),headers:{"Content-Type":"application/x-www-form-urlencoded"},callback:this.map.editor.requestComplete,proxy:this.proxy,scope:this.map.editor})}},CLASS_NAME:"OpenLayers.Editor.Control.CleanFeature"});
OpenLayers.Editor.Control.DragFeature=OpenLayers.Class(OpenLayers.Control.DragFeature,{title:OpenLayers.i18n("oleDragFeature"),EVENT_TYPES:["activate","deactivate","dragstart","dragdrag","dragcomplete","dragenter","dragleave"],initialize:function(a,b){OpenLayers.Control.DragFeature.prototype.initialize.apply(this,[a,b]);this.title=OpenLayers.i18n("oleDragFeature")},onStart:function(a,b){this.events.triggerEvent("dragstart",{feature:a,pixel:b})},onDrag:function(a,b){this.events.triggerEvent("dragdrag",
{feature:a,pixel:b})},onComplete:function(a,b){this.events.triggerEvent("dragcomplete",{feature:a,pixel:b});this.layer.events.triggerEvent("afterfeaturemodified",{feature:a})},onEnter:function(a){this.events.triggerEvent("dragenter",{feature:a})},onLeave:function(a){this.events.triggerEvent("dragleave",{feature:a})},CLASS_NAME:"OpenLayers.Editor.Control.DragFeature"});
OpenLayers.Editor.Control.DeleteFeature=OpenLayers.Class(OpenLayers.Control.Button,{layer:null,title:OpenLayers.i18n("oleDeleteFeature"),initialize:function(a,b){this.layer=a;this.title=OpenLayers.i18n("oleDeleteFeature");OpenLayers.Control.Button.prototype.initialize.apply(this,[b]);this.trigger=this.deleteFeature;this.displayClass="oleControlDisabled "+this.displayClass},deleteFeature:function(){if(this.layer.selectedFeatures.length>0){this.layer.destroyFeatures(this.layer.selectedFeatures);this.layer.events.triggerEvent("featureunselected")}},
CLASS_NAME:"OpenLayers.Editor.Control.DeleteFeature"});
OpenLayers.Editor.Control.Dialog=OpenLayers.Class(OpenLayers.Control,{dialogDiv:null,buttonClass:null,inputTextClass:null,modal:true,initialize:function(a){OpenLayers.Control.prototype.initialize.apply(this,[a])},show:function(a){var b,c;OpenLayers.Util.indexOf(this.map.viewPortDiv.childNodes,this.dialogDiv)>-1&&this.map.viewPortDiv.removeChild(this.dialogDiv);a||(a={});this.dialogDiv=document.createElement("div");OpenLayers.Element.addClass(this.dialogDiv,"oleDialog");a.toolbox?OpenLayers.Element.addClass(this.dialogDiv,
"oleDialogToolbar"):OpenLayers.Element.addClass(this.div,"oleFadeMap");if(a.title){b=document.createElement("h3");b.innerHTML=a.title;this.dialogDiv.appendChild(b)}if(typeof a.content==="string"){b=document.createElement("div");b.innerHTML=a.content;this.dialogDiv.appendChild(b)}else OpenLayers.Util.isElement(a.content)&&this.dialogDiv.appendChild(a.content);if(a.save){b=this.getButton(OpenLayers.i18n("oleDialogCancelButton"));this.dialogDiv.appendChild(b);c=this.getButton(OpenLayers.i18n(a.saveButtonText?
a.saveButtonText:"oleDialogSaveButton"));this.dialogDiv.appendChild(c);OpenLayers.Event.observe(b,"click",OpenLayers.Function.bind(this.hide,this));a.noHideOnSave||OpenLayers.Event.observe(c,"click",OpenLayers.Function.bind(this.hide,this));OpenLayers.Event.observe(c,"click",a.save);a.cancel&&OpenLayers.Event.observe(b,"click",a.cancel)}else if(!a.toolbox){b=this.getButton(OpenLayers.i18n("oleDialogOkButton"));this.dialogDiv.appendChild(b);OpenLayers.Event.observe(b,"click",OpenLayers.Function.bind(this.hide,
this));a.close&&OpenLayers.Event.observe(b,"click",a.close)}a=this.dialogDiv.getElementsByTagName("input");for(b=0;b<a.length;b++)a[b].getAttribute("type")=="text"&&OpenLayers.Element.addClass(a[b],this.inputTextClass);this.map.viewPortDiv.appendChild(this.dialogDiv);OpenLayers.Event.observe(this.div,"click",this.ignoreEvent);OpenLayers.Event.observe(this.div,"mousedown",this.ignoreEvent);OpenLayers.Event.observe(this.div,"dblclick",this.ignoreEvent);OpenLayers.Event.observe(this.dialogDiv,"mousedown",
this.ignoreEvent);OpenLayers.Event.observe(this.dialogDiv,"dblclick",this.ignoreEvent)},hide:function(){if(this.dialogDiv){this.map.viewPortDiv.removeChild(this.dialogDiv);OpenLayers.Element.removeClass(this.div,"oleFadeMap");this.dialogDiv=null}},ignoreEvent:function(a){OpenLayers.Event.stop(a,true)},getButton:function(a){var b=document.createElement("input");b.value=a;b.type="button";OpenLayers.Element.addClass(b,this.buttonClass);return b},CLASS_NAME:"OpenLayers.Editor.Control.Dialog"});
OpenLayers.Editor.Control.DrawHole=OpenLayers.Class(OpenLayers.Control.DrawFeature,{minArea:0,title:OpenLayers.i18n("oleDrawHole"),initialize:function(a,b){this.callbacks=OpenLayers.Util.extend(this.callbacks,{point:function(c){this.layer.events.triggerEvent("pointadded",{point:c})}});OpenLayers.Control.DrawFeature.prototype.initialize.apply(this,[a,OpenLayers.Handler.Polygon,b]);this.title=OpenLayers.i18n("oleDrawHole")},drawFeature:function(a){var b=new OpenLayers.Feature.Vector(a);b.state=OpenLayers.State.INSERT;
if(this.layer.events.triggerEvent("sketchcomplete",{feature:b})!==false&&a.getArea()>=this.minArea){b=a.getVertices();var c,d=0,e=this.layer.features.length;a:for(;d<e;d++){var f=this.layer.features[d];c=true;for(var g=0,h=b.length;g<h;g++)f.geometry.intersects(b[g])||(c=false);if(c){f.state=OpenLayers.State.UPDATE;this.layer.events.triggerEvent("beforefeaturemodified",{feature:f});f.geometry.components.push(a.components[0]);this.layer.drawFeature(f);this.layer.events.triggerEvent("featuremodified",
{feature:f});this.layer.events.triggerEvent("afterfeaturemodified",{feature:f});break a}}}},CLASS_NAME:"OpenLayers.Editor.Control.DrawHole"});
OpenLayers.Editor.Control.DrawPolygon=OpenLayers.Class(OpenLayers.Control.DrawFeature,{minArea:0,title:OpenLayers.i18n("oleDrawPolygon"),initialize:function(a,b){this.callbacks=OpenLayers.Util.extend(this.callbacks,{point:function(c){this.layer.events.triggerEvent("pointadded",{point:c})}});OpenLayers.Control.DrawFeature.prototype.initialize.apply(this,[a,OpenLayers.Handler.Polygon,b]);this.title=OpenLayers.i18n("oleDrawPolygon")},drawFeature:function(a){var b=new OpenLayers.Feature.Vector(a);if(this.layer.events.triggerEvent("sketchcomplete",
{feature:b})!==false&&a.getArea()>=this.minArea){b.state=OpenLayers.State.INSERT;this.layer.addFeatures([b]);this.featureAdded(b);this.events.triggerEvent("featureadded",{feature:b})}},CLASS_NAME:"OpenLayers.Editor.Control.DrawPolygon"});
OpenLayers.Editor.Control.DrawPath=OpenLayers.Class(OpenLayers.Control.DrawFeature,{minLength:0,title:OpenLayers.i18n("oleDrawPath"),initialize:function(a,b){this.callbacks=OpenLayers.Util.extend(this.callbacks,{point:function(c){this.layer.events.triggerEvent("pointadded",{point:c})}});OpenLayers.Control.DrawFeature.prototype.initialize.apply(this,[a,OpenLayers.Handler.Path,b]);this.title=OpenLayers.i18n("oleDrawPath")},drawFeature:function(a){var b=new OpenLayers.Feature.Vector(a);if(this.layer.events.triggerEvent("sketchcomplete",
{feature:b})!==false&&a.getLength()>=this.minLength){b.state=OpenLayers.State.INSERT;this.layer.addFeatures([b]);this.featureAdded(b);this.events.triggerEvent("featureadded",{feature:b})}},CLASS_NAME:"OpenLayers.Editor.Control.DrawPath"});
OpenLayers.Editor.Control.DrawPoint=OpenLayers.Class(OpenLayers.Control.DrawFeature,{title:OpenLayers.i18n("oleDrawPoint"),featureType:"point",initialize:function(a,b){this.callbacks=OpenLayers.Util.extend(this.callbacks,{point:function(c){this.layer.events.triggerEvent("pointadded",{point:c})}});OpenLayers.Control.DrawFeature.prototype.initialize.apply(this,[a,OpenLayers.Handler.Point,b]);this.title=OpenLayers.i18n("oleDrawPoint")},drawFeature:function(a){a=new OpenLayers.Feature.Vector(a);var b=
this.layer.events.triggerEvent("sketchcomplete",{feature:a});a.featureType=this.featureType;if(b!==false){this.events.triggerEvent("beforefeatureadded",{feature:a});a.state=OpenLayers.State.INSERT;this.layer.addFeatures([a]);this.featureAdded(a);this.events.triggerEvent("featureadded",{feature:a})}},CLASS_NAME:"OpenLayers.Editor.Control.DrawPoint"});
OpenLayers.Editor.Control.DrawRegular=OpenLayers.Class(OpenLayers.Control.DrawFeature,{minArea:0,title:OpenLayers.i18n("oleDrawRegular"),sides:[3,4,5,6,40],initialize:function(a,b){this.callbacks=OpenLayers.Util.extend(this.callbacks,{point:function(c){this.layer.events.triggerEvent("pointadded",{point:c})}});OpenLayers.Control.DrawFeature.prototype.initialize.apply(this,[a,OpenLayers.Handler.RegularPolygon,b]);this.title=OpenLayers.i18n("oleDrawRegular")},activate:function(){var a=OpenLayers.Control.Button.prototype.activate.call(this),
b,c,d;b=document.createElement("div");c=document.createElement("div");OpenLayers.Element.addClass(c,"oleDrawRegularIrregular");d=document.createElement("input");d.type="checkbox";d.id="oleCADToolsDialogIrregular";d.value="true";OpenLayers.Event.observe(d,"change",OpenLayers.Function.bind(function(g){this.handler.setOptions({irregular:g.target.checked})},this));c.appendChild(d);d=document.createElement("label");d.htmlFor="oleCADToolsDialogIrregular";d.appendChild(document.createTextNode(OpenLayers.i18n("oleDrawRegularIrregular")));
c.appendChild(d);b.appendChild(c);c=document.createElement("div");var e=document.createElement("select");e.id="oleCADToolsDialogSides";for(var f=0;f<this.sides.length;++f){d=document.createElement("option");d.value=this.sides[f];d.text=this.sides[f]<20?OpenLayers.i18n("oleDrawRegularSides"+this.sides[f]):OpenLayers.i18n("oleDrawRegularCircle");e.appendChild(d)}OpenLayers.Event.observe(e,"change",OpenLayers.Function.bind(function(g){this.handler.setOptions({sides:parseInt(g.target.value)})},this));
this.handler.setOptions({sides:parseInt(e.value)});c.appendChild(e);d=document.createElement("label");d.htmlFor="oleCADToolsDialogSides";d.appendChild(document.createTextNode(OpenLayers.i18n("oleDrawRegularShape")));c.appendChild(d);b.appendChild(c);this.map.editor.dialog.show({content:b,toolbox:true});return a},deactivate:function(){var a=OpenLayers.Control.Button.prototype.deactivate.call(this);a&&typeof this.map.editor.dialog.hide=="function"&&this.map.editor.dialog.hide();return a},drawFeature:function(a){var b=
new OpenLayers.Feature.Vector(a);if(this.layer.events.triggerEvent("sketchcomplete",{feature:b})!==false&&a.getArea()>=this.minArea){b.state=OpenLayers.State.INSERT;this.layer.addFeatures([b]);this.featureAdded(b);this.events.triggerEvent("featureadded",{feature:b})}},CLASS_NAME:"OpenLayers.Editor.Control.DrawRegular"});
OpenLayers.Editor.Control.EditorPanel=OpenLayers.Class(OpenLayers.Control.Panel,{autoActivate:false,initialize:function(a,b){OpenLayers.Control.Panel.prototype.initialize.apply(this,[b])},draw:function(){OpenLayers.Control.Panel.prototype.draw.apply(this,arguments);if(!this.active)this.div.style.display="none";return this.div},redraw:function(){if(!this.active)this.div.style.display="none";OpenLayers.Control.Panel.prototype.redraw.apply(this,arguments);if(this.active)this.div.style.display=""},CLASS_NAME:"OpenLayers.Editor.Control.EditorPanel"});
OpenLayers.Editor.Control.ImportFeature=OpenLayers.Class(OpenLayers.Control.Button,{layer:null,title:OpenLayers.i18n("oleImportFeature"),initialize:function(a,b){this.layer=a;OpenLayers.Control.Button.prototype.initialize.apply(this,[b]);this.trigger=this.importFeature;this.title=OpenLayers.i18n("oleImportFeature");this.displayClass="oleControlDisabled "+this.displayClass},importFeature:function(){var a=[];if(this.map.editor.sourceLayers.length>0){for(var b=0,c=this.map.editor.sourceLayers.length;b<
c;b++){for(var d=0,e=this.map.editor.sourceLayers[b].selectedFeatures.length;d<e;d++){this.map.editor.sourceLayers[b].selectedFeatures[d].renderIntent="default";a.push(this.map.editor.sourceLayers[b].selectedFeatures[d])}this.map.editor.sourceLayers[b].removeFeatures(this.map.editor.sourceLayers[b].selectedFeatures);this.map.editor.sourceLayers[b].events.triggerEvent("featureunselected")}if(a.length>0)this.layer.addFeatures(a);else return this.map.editor.showStatus("error",OpenLayers.i18n("oleImportFeatureSourceFeature"))}else return this.map.editor.showStatus("error",
OpenLayers.i18n("oleImportFeatureSourceLayer"))},CLASS_NAME:"OpenLayers.Editor.Control.ImportFeature"});
OpenLayers.Editor.Control.LayerSettings=OpenLayers.Class(OpenLayers.Control,{currentLayer:null,layerSwitcher:null,initialize:function(a,b){OpenLayers.Control.prototype.initialize.apply(this,[b]);this.layerSwitcher=a.map.getControlsByClass("OpenLayers.Control.LayerSwitcher")[0];this.layerSwitcher instanceof OpenLayers.Control.LayerSwitcher&&OpenLayers.Event.observe(this.layerSwitcher.maximizeDiv,"click",OpenLayers.Function.bind(this.redraw,this))},redraw:function(){var a,b;this.layerSwitcher.dataLayersDiv.innerHTML=
"";for(var c=0,d=this.layerSwitcher.dataLayers.length;c<d;c++){var e=this.layerSwitcher.dataLayers[c];a=document.createElement("input");a.type="checkbox";a.id="list"+e.layer.name;a.name=e.layer.name;if(e.layer.visibility){a.checked="checked";a.defaultChecked="selected"}this.layerSwitcher.dataLayersDiv.appendChild(a);b=document.createElement("span");b.innerHTML=e.layer.name;OpenLayers.Element.addClass(b,"labelSpan");this.layerSwitcher.dataLayersDiv.appendChild(b);this.layerSwitcher.dataLayersDiv.appendChild(document.createElement("br"));
OpenLayers.Event.observe(a,"click",OpenLayers.Function.bind(this.toggleLayerVisibility,this,e.layer.name));OpenLayers.Event.observe(b,"click",OpenLayers.Function.bind(this.showLayerSettings,this,e.layer.name))}},showLayerSettings:function(a){var b,c,d,e;this.currentLayer=this.map.getLayersByName(a)[0];b=document.createElement("div");c=document.createElement("h4");c.innerHTML=OpenLayers.i18n("oleLayerSettingsOpacityHeader");b.appendChild(c);e=this.currentLayer.opacity?this.currentLayer.opacity:1;c=
document.createElement("input");c.type="text";c.size="2";c.value=(e*100).toFixed(0);OpenLayers.Event.observe(c,"change",OpenLayers.Function.bind(this.changeLayerOpacity,this,c));b.appendChild(c);if(this.currentLayer instanceof OpenLayers.Layer.Vector){c=document.createElement("h4");c.innerHTML=OpenLayers.i18n("oleLayerSettingsImportHeader");c.style.marginTop="10px";b.appendChild(c);e=document.createElement("input");e.type="checkbox";e.name="import"+this.currentLayer.name;b.appendChild(e);c=document.createElement("label");
c.htmlFor="import"+this.currentLayer.name;c.innerHTML=OpenLayers.i18n("oleLayerSettingsImportLabel");b.appendChild(c);b.appendChild(document.createElement("p"));c=0;for(d=this.map.editor.sourceLayers.length;c<d;c++)if(this.currentLayer.id==this.map.editor.sourceLayers[c].id){e.writeAttribute("checked","checked");e.defaultChecked="selected";break}OpenLayers.Event.observe(e,"click",OpenLayers.Function.bind(this.toggleExportFeature,this))}e=this.getLegendGraphics(this.currentLayer);if(e.length>0){c=
document.createElement("h4");c.innerHTML=OpenLayers.i18n("oleLayerSettingsLegendHeader");c.style.marginTop="10px";b.appendChild(c);for(c=0;c<e.length;c++){d=document.createElement("img");d.src=e[c];b.appendChild(d)}}this.map.editor.dialog.show({content:b,title:a})},toggleExportFeature:function(){for(var a=true,b=0,c=this.map.editor.sourceLayers.length;b<c;b++)if(this.currentLayer.id==this.map.editor.sourceLayers[b].id){this.map.editor.sourceLayers.splice(b,1);a=false;break}a&&this.map.editor.sourceLayers.push(this.currentLayer)},
toggleLayerVisibility:function(a){a=this.map.getLayersByName(a)[0];a.visibility?a.setVisibility(false):a.setVisibility(true);this.redraw()},changeLayerOpacity:function(a){this.currentLayer.setOpacity(a.value/100)},getLegendGraphics:function(a){var b=[];if(a.legendGraphics)b=a.legendGraphics;else if(a instanceof OpenLayers.Layer.WMS)for(var c=a.params.LAYERS.split(","),d=0;d<c.length;d++){var e=c[d],f=a.url;f+=f.indexOf("?")===-1?"?":"";f+="&SERVICE=WMS";f+="&VERSION=1.1.1";f+="&REQUEST=GetLegendGraphic";
f+="&FORMAT=image/png";f+="&LAYER="+e;b.push(f)}return b},CLASS_NAME:"OpenLayers.Editor.Control.LayerSettings"});
OpenLayers.Editor.Control.MergeFeature=OpenLayers.Class(OpenLayers.Control.Button,{proxy:null,title:OpenLayers.i18n("oleMergeFeature"),initialize:function(a,b){this.layer=a;OpenLayers.Control.Button.prototype.initialize.apply(this,[b]);this.trigger=this.mergeFeature;this.title=OpenLayers.i18n("oleMergeFeature");this.displayClass="oleControlDisabled "+this.displayClass},mergeFeature:function(){if(this.layer.selectedFeatures.length<2)this.map.editor.showStatus("error",OpenLayers.i18n("oleMergeFeatureSelectFeature"));
else{var a=(new OpenLayers.Format.WKT).write(this.layer.selectedFeatures);this.map.editor.startWaiting(this.panel_div);OpenLayers.Request.POST({url:this.map.editor.oleUrl+"process/merge",data:OpenLayers.Util.getParameterString({geo:a}),headers:{"Content-Type":"application/x-www-form-urlencoded"},callback:this.map.editor.requestComplete,proxy:this.proxy,scope:this.map.editor})}},CLASS_NAME:"OpenLayers.Editor.Control.MergeFeature"});
OpenLayers.Editor.Control.FixedAngleDrawing=OpenLayers.Class(OpenLayers.Control,{CLASS_NAME:"OpenLayers.Editor.Control.FixedAngleDrawing",active:false,sketchVerticesAmount:null,guides:null,initialize:function(a){this.guides=[];OpenLayers.Control.prototype.initialize.call(this);this.layer=a},activate:function(){var a=OpenLayers.Control.prototype.activate.call(this);a&&this.layer.events.on({sketchstarted:this.onSketchStarted,sketchmodified:this.onSketchModified,sketchcomplete:this.onSketchComplete,
scope:this});return a},deactivate:function(){var a=OpenLayers.Control.prototype.deactivate.call(this);a&&this.layer.events.un({sketchstarted:this.onSketchStarted,sketchmodified:this.onSketchModified,sketchcomplete:this.onSketchComplete,scope:this});return a},onSketchModified:function(a){a=a.feature.geometry.getVertices();if(a.length>2&&this.sketchVerticesAmount!==a.length){this.removeGuides();this.sketchVerticesAmount=a.length;this.updateGuideLines(a[a.length-3],a[a.length-2]);var b=this.getSnappingGuideLayer(),
c=-1/b.getLine({x1:a[0].x,y1:a[0].y,x2:a[1].x,y2:a[1].y}).m;this.guides.push(b.addLine({m:c,b:a[0].y-c*a[0].x}))}},onSketchComplete:function(){this.removeGuides()},removeGuides:function(){this.getSnappingGuideLayer().removeFeatures(this.guides);this.guides=[]},onSketchStarted:function(a){var b=a.feature,c;if(b.geometry instanceof OpenLayers.Geometry.LineString||b.geometry instanceof OpenLayers.Geometry.Polygon){for(a=0;a<this.map.controls.length;a++){var d=this.map.controls[a];if(d.active&&d.handler instanceof
OpenLayers.Handler.Path){c=d.handler.layer;break}}c.events.on({featureremoved:function(e){if(e.feature.id===b.id){this.sketchVerticesAmount=null;this.getSnappingGuideLayer().destroyFeatures()}},scope:this})}},getSnappingGuideLayer:function(){return this.map.getLayersByClass("OpenLayers.Editor.Layer.Snapping")[0]},updateGuideLines:function(a,b){var c=this.getSnappingGuideLayer(),d=-1/((b.y-a.y)/(b.x-a.x));this.guides.push(c.addLine({m:d,b:b.y-d*b.x,x:b.x}))}});
OpenLayers.Editor.Layer=OpenLayers.Class(OpenLayers.Layer,{initialize:function(a){OpenLayers.Control.prototype.initialize.apply(this,[a])},CLASS_NAME:"OpenLayers.Editor.Layer"});
OpenLayers.Editor.Layer.Snapping=OpenLayers.Class(OpenLayers.Layer.Vector,{CLASS_NAME:"OpenLayers.Editor.Layer.Snapping",intersectionPoints:null,initialize:function(a,b){this.intersectionPoints=[];if(b.styleMap===undefined)b.styleMap=new OpenLayers.StyleMap({"default":new OpenLayers.Style({strokeColor:"#ff00ff",strokeOpacity:0.5,strokeWidth:1,strokeDashstyle:"solid",fillColor:"#ff00ff"},{rules:[new OpenLayers.Rule({evaluate:function(c){return c.geometry instanceof OpenLayers.Geometry.LineString},
symbolizer:{strokeDashstyle:"longdash"}}),new OpenLayers.Rule({evaluate:function(c){return c.geometry instanceof OpenLayers.Geometry.Point},symbolizer:{graphicName:"cross",pointRadius:3,strokeWidth:0}}),new OpenLayers.Rule]})});OpenLayers.Layer.Vector.prototype.initialize.call(this,a,b)},addGuides:function(a,b){for(var c=[],d=0;d<a.length;d++)c[d]=a[d]instanceof OpenLayers.Feature.Vector?a[d]:new OpenLayers.Feature.Vector(a[d]);OpenLayers.Layer.Vector.prototype.addFeatures.call(this,c,b);return c},
getLine:function(a){if(a.x1===a.x2)return{m:Infinity,x:a.x1};var b=(a.y2-a.y1)/(a.x2-a.x1);return{m:b,b:a.y2-b*a.x2}},addLine:function(a){var b=this.map.getMaxExtent();a=a.m===Infinity?new OpenLayers.Feature.Vector(new OpenLayers.Geometry.LineString([new OpenLayers.Geometry.Point(a.x,b.top),new OpenLayers.Geometry.Point(a.x,b.bottom)])):new OpenLayers.Feature.Vector(new OpenLayers.Geometry.LineString([this.createWorldBoundaryPoint(a.m,b.left,a.b,b),this.createWorldBoundaryPoint(a.m,b.right,a.b,b)]));
this.addFeatures([a]);this.rebuildIntersectionPoints();return a},createWorldBoundaryPoint:function(a,b,c,d){var e=a*b+c;b=e>d.top?(d.top-c)/a:e<d.bottom?(d.bottom-c)/a:b;return new OpenLayers.Geometry.Point(b,a*b+c)},rebuildIntersectionPoints:function(){var a=this.map.getMaxExtent();this.removeFeatures(this.intersectionPoints);this.intersectionPoints=[];this.features.forEach(function(b){b.geometry instanceof OpenLayers.Geometry.Curve&&b.geometry.getSortedSegments().forEach(function(c){var d=this.getLine(c);
this.features.forEach(function(e){e.geometry instanceof OpenLayers.Geometry.Curve&&e.geometry.getSortedSegments().forEach(function(f){f=this.getLine(f);if(d.m!==f.m){f=(f.b-d.b)/(d.m-f.m);var g=d.m*f+d.b;f>=a.left&&f<=a.right&&g>=a.bottom&&g<=a.top&&this.intersectionPoints.push(new OpenLayers.Feature.Vector(new OpenLayers.Geometry.Point(f,g)))}},this)},this)},this)},this);this.addFeatures(this.intersectionPoints)},removeFeatures:function(a){OpenLayers.Layer.Vector.prototype.removeFeatures.apply(this,
arguments);a!==this.intersectionPoints&&this.rebuildIntersectionPoints()},drawFeature:function(a){var b=OpenLayers.Layer.Vector.prototype.drawFeature.apply(this,arguments);if(this.unrenderedFeatures[a.id]===a){var c=this.map.getExtent();if(a.geometry.intersects(c.toGeometry()))if(a.geometry instanceof OpenLayers.Geometry.LineString&&a.geometry.components.length===2){var d=a.geometry.getSortedSegments()[0],e=this.getLine(d);if(e.m===Infinity){b=new OpenLayers.Geometry.Point(e.x,c.top);e=new OpenLayers.Geometry.Point(e.x,
c.bottom)}else{b=this.createWorldBoundaryPoint(e.m,c.left,e.b,c);e=this.createWorldBoundaryPoint(e.m,c.right,e.b,c)}c=a.geometry.components[0];c.x=b.x;c.y=b.y;var f=a.geometry.components[1];f.x=e.x;f.y=e.y;b=OpenLayers.Layer.Vector.prototype.drawFeature.apply(this,arguments);c.x=d.x1;c.y=d.y1;f.x=d.x2;f.y=d.y2}else console.warn("Failed to render a feature",a)}return b},moveTo:function(){OpenLayers.Layer.Vector.prototype.moveTo.apply(this,arguments);this.features.forEach(function(a){this.drawFeature(a)},
this)}});
OpenLayers.Editor.Control.SnappingSettings=OpenLayers.Class(OpenLayers.Control.Button,{title:OpenLayers.i18n("oleSnappingSettings"),layer:null,snapping:new OpenLayers.Control.Snapping,tolerance:10,snappingLayers:null,snappingGuideLayer:null,layerListDiv:null,toleranceInput:null,initialize:function(a,b){this.snappingLayers=[];this.layer=a;OpenLayers.Control.Button.prototype.initialize.apply(this,[b]);this.trigger=OpenLayers.Function.bind(this.openSnappingDialog,this);this.events.register("deactivate",this,
this.onDeactivate);this.title=OpenLayers.i18n("oleSnappingSettings")},deactivate:function(){OpenLayers.Control.Button.prototype.deactivate.call(this);this.map&&this.map.editor&&this.map.editor.dialog&&this.map.editor.dialog.hide()},onDeactivate:function(){this.snapping.active&&this.activate()},openSnappingDialog:function(){var a,b;this.activate();this.layerListDiv=document.createElement("div");a=document.createElement("div");b=document.createElement("h4");b.innerHTML=OpenLayers.i18n("oleSnappingSettingsTolerance");
a.appendChild(b);this.toleranceInput=document.createElement("input");this.toleranceInput.type="text";this.toleranceInput.size=4;this.toleranceInput.value=this.tolerance;a.appendChild(this.toleranceInput);a.appendChild(document.createTextNode(OpenLayers.i18n("olePixelUnit")));b=document.createElement("h4");b.innerHTML=OpenLayers.i18n("oleSnappingSettingsLayer");a.appendChild(b);a.appendChild(this.layerListDiv);this.map.editor.dialog.show({content:a,title:OpenLayers.i18n("oleSnappingSettings"),close:OpenLayers.Function.bind(this.changeSnapping,
this)});this.redraw()},redraw:function(){var a,b,c;this.layerListDiv.innerHTML="";for(var d=0;d<this.map.layers.length;d++){a=this.map.layers[d];if(!(a instanceof OpenLayers.Layer.Vector.RootContainer)&&a instanceof OpenLayers.Layer.Vector&&!(a instanceof OpenLayers.Editor.Layer.Snapping)&&a.name.search(/OpenLayers.Handler.+/)==-1){c=document.createElement("div");b=document.createElement("input");b.type="checkbox";b.name="snappingLayer";b.id="Snapping."+a.id;b.value="true";if(this.snappingLayers.indexOf(a)>=
0){b.checked="checked";b.defaultChecked="selected"}c.appendChild(b);OpenLayers.Event.observe(b,"click",OpenLayers.Function.bind(this.setLayerSnapping,this,a,b.checked));b=document.createElement("label");b.setAttribute("for","Snapping."+a.id);b.innerHTML=a.name;OpenLayers.Event.observe(b,"click",OpenLayers.Function.bind(function(e){OpenLayers.Event.stop(e,true)},this));c.appendChild(b);this.layerListDiv.appendChild(c)}}},setLayerSnapping:function(a,b){b?this.snappingLayers.splice(this.snappingLayers.indexOf(a),
1):this.snappingLayers.push(a);this.redraw()},changeSnapping:function(){this.tolerance=parseInt(this.toleranceInput.value,10);if(this.snappingLayers.length>0){this.snapping.deactivate();for(var a=[],b=0;b<this.snappingLayers.length;b++)a.push({layer:this.snappingLayers[b],tolerance:this.tolerance});this.snapping=new OpenLayers.Control.Snapping({layer:this.layer,targets:a});for(b=0;b<a.length;b++)a[b].layer.moveTo(this.map.getExtent(),false,false);this.snapping.activate()}else if(this.snapping.active){this.snapping.deactivate();
this.snapping.targets=null}this.snapping.active||this.deactivate()},setMap:function(){OpenLayers.Control.Button.prototype.setMap.apply(this,arguments);if(this.snappingGuideLayer===null)this.snappingGuideLayer=this.createSnappingGuideLayer()},createSnappingGuideLayer:function(){var a=new OpenLayers.Editor.Layer.Snapping(OpenLayers.i18n("Snapping Layer"),{visibility:false});this.map.addLayer(a);return a},CLASS_NAME:"OpenLayers.Editor.Control.SnappingSettings"});
OpenLayers.Editor.Control.SplitFeature=OpenLayers.Class(OpenLayers.Control.DrawFeature,{proxy:null,title:OpenLayers.i18n("oleSplitFeature"),initialize:function(a,b){OpenLayers.Control.DrawFeature.prototype.initialize.apply(this,[a,OpenLayers.Handler.Path,b]);this.events.register("activate",this,this.test);this.title=OpenLayers.i18n("oleSplitFeature");this.displayClass="oleControlDisabled "+this.displayClass},test:function(){this.layer.selectedFeatures.length<1&&this.deactivate()},drawFeature:function(a){a=
new OpenLayers.Feature.Vector(a);var b=new OpenLayers.Format.WKT,c=this.layer.events.triggerEvent("sketchcomplete",{feature:a});this.deactivate();if(c!==false)if(this.layer.selectedFeatures.length>0){c=b.write(this.layer.selectedFeatures);a=b.write(a);this.map.editor.startWaiting(this.panel_div);OpenLayers.Request.POST({url:this.map.editor.oleUrl+"process/split",data:OpenLayers.Util.getParameterString({cut:a,geo:c}),headers:{"Content-Type":"application/x-www-form-urlencoded"},callback:this.map.editor.requestComplete,
proxy:this.proxy,scope:this.map.editor})}},CLASS_NAME:"OpenLayers.Editor.Control.SplitFeature"});
OpenLayers.Editor.Control.UndoRedo=OpenLayers.Class(OpenLayers.Control,{layer:null,handler:null,autoActivate:true,KEY_Z:90,KEY_Y:89,onUndo:function(){},onRedo:function(){},onRemoveFeature:function(){},undoStack:null,redoStack:null,currentState:null,initialize:function(a,b){this.layer=a;OpenLayers.Control.prototype.initialize.apply(this,[b]);this.layer.events.register("featureadded",this,this.register);this.layer.events.register("afterfeaturemodified",this,this.register);this.undoStack=[];this.redoStack=
[]},draw:function(){this.handler=new OpenLayers.Handler.Keyboard(this,{keydown:this.handleKeydown})},handleKeydown:function(a){if(a.keyCode===this.KEY_Z&&a.ctrlKey===true&&a.shiftKey===false)this.undo();else if(a.ctrlKey===true&&(a.keyCode===this.KEY_Y||a.keyCode===this.KEY_Z&&a.shiftKey===true))this.redo()},undo:function(){var a=this.moveBetweenStacks(this.undoStack,this.redoStack,true);a&&this.onUndo(a)},redo:function(){var a=this.moveBetweenStacks(this.redoStack,this.undoStack,false);a&&this.onRedo(a)},
moveBetweenStacks:function(a,b,c){if(a.length>0){this.map.editor.editLayer.removeAllFeatures();a=a.pop();b.push(this.currentState);if(a){b=Array(d);var d=a.length;for(c=0;c<d;++c)b[c]=a[c].clone();this.currentState=b;this.map.editor.editLayer.addFeatures(a,{silent:true})}else this.currentState=null}else if(this.currentState&&c){b.push(this.currentState);this.map.editor.editLayer.removeAllFeatures();this.currentState=null}},register:function(){for(var a=this.map.editor.editLayer.features,b=a.length,
c=Array(b),d=0;d<b;++d)c[d]=a[d].clone();this.currentState&&this.undoStack.push(this.currentState);this.currentState=c;this.redoStack=[]},CLASS_NAME:"OpenLayers.Editor.Control.UndoRedo"});
OpenLayers.Editor.Control.FixedAngleDrawing=OpenLayers.Class(OpenLayers.Control,{CLASS_NAME:"OpenLayers.Editor.Control.FixedAngleDrawing",active:false,sketchVerticesAmount:null,guides:null,initialize:function(a){this.guides=[];OpenLayers.Control.prototype.initialize.call(this);this.layer=a},activate:function(){var a=OpenLayers.Control.prototype.activate.call(this);a&&this.layer.events.on({sketchstarted:this.onSketchStarted,sketchmodified:this.onSketchModified,sketchcomplete:this.onSketchComplete,
scope:this});return a},deactivate:function(){var a=OpenLayers.Control.prototype.deactivate.call(this);a&&this.layer.events.un({sketchstarted:this.onSketchStarted,sketchmodified:this.onSketchModified,sketchcomplete:this.onSketchComplete,scope:this});return a},onSketchModified:function(a){a=a.feature.geometry.getVertices();if(a.length>2&&this.sketchVerticesAmount!==a.length){this.removeGuides();this.sketchVerticesAmount=a.length;this.updateGuideLines(a[a.length-3],a[a.length-2]);var b=this.getSnappingGuideLayer(),
c=-1/b.getLine({x1:a[0].x,y1:a[0].y,x2:a[1].x,y2:a[1].y}).m;this.guides.push(b.addLine({m:c,b:a[0].y-c*a[0].x}))}},onSketchComplete:function(){this.removeGuides()},removeGuides:function(){this.getSnappingGuideLayer().removeFeatures(this.guides);this.guides=[]},onSketchStarted:function(a){var b=a.feature,c;if(b.geometry instanceof OpenLayers.Geometry.LineString||b.geometry instanceof OpenLayers.Geometry.Polygon){for(a=0;a<this.map.controls.length;a++){var d=this.map.controls[a];if(d.active&&d.handler instanceof
OpenLayers.Handler.Path){c=d.handler.layer;break}}c.events.on({featureremoved:function(e){if(e.feature.id===b.id){this.sketchVerticesAmount=null;this.getSnappingGuideLayer().destroyFeatures()}},scope:this})}},getSnappingGuideLayer:function(){return this.map.getLayersByClass("OpenLayers.Editor.Layer.Snapping")[0]},updateGuideLines:function(a,b){var c=this.getSnappingGuideLayer(),d=-1/((b.y-a.y)/(b.x-a.x));this.guides.push(c.addLine({m:d,b:b.y-d*b.x,x:b.x}))}});
OpenLayers.Editor.Control.CADTools=OpenLayers.Class(OpenLayers.Control.Button,{title:OpenLayers.i18n("oleCADTools"),layer:null,parallelDrawingButton:null,guidedDrawingButton:null,tolerance:10,fixedAngleDrawingControl:null,parallelDrawingControl:null,snappingControl:null,initialize:function(a,b){this.layer=a;this.fixedAngleDrawingControl=new OpenLayers.Editor.Control.FixedAngleDrawing(a);this.parallelDrawingControl=new OpenLayers.Editor.Control.ParallelDrawing(a);OpenLayers.Control.Button.prototype.initialize.apply(this,
[b]);this.trigger=OpenLayers.Function.bind(this.openCADToolsDialog,this);this.events.register("deactivate",this,this.onDeactivate);this.title=OpenLayers.i18n("oleCADTools")},activate:function(){var a=OpenLayers.Control.Button.prototype.activate.call(this);a&&this.snappingControl.activate();return a},deactivate:function(){var a=OpenLayers.Control.Button.prototype.deactivate.call(this);a&&this.snappingControl.deactivate();return a},onDeactivate:function(){this.deactivate();this.map.editor.dialog.hide()},
setMap:function(a){OpenLayers.Control.Button.prototype.setMap.call(this,a);this.map.addControl(this.fixedAngleDrawingControl);this.map.addControl(this.parallelDrawingControl);this.snappingControl=new OpenLayers.Control.Snapping({layer:this.layer,targets:[{layer:this.map.getLayersByClass("OpenLayers.Editor.Layer.Snapping")[0],tolerance:this.tolerance}]})},openCADToolsDialog:function(){if(this.active){this.deactivate();this.map.editor.dialog.hide()}else{this.activate();var a,b;a=document.createElement("div");
b=document.createElement("div");b.className="olEditorControlEditorPanel olEditorCADToolsToolbar";b.style.top="10px";b.style.right="10px";this.parallelDrawingButton=document.createElement("div");this.parallelDrawingButton.title=OpenLayers.i18n("oleCADToolsDialogParallelDrawing");this.parallelDrawingButton.className=this.parallelDrawingControl.active?"olEditorParallelDrawingActive":"olEditorParallelDrawingInactive";OpenLayers.Event.observe(this.parallelDrawingButton,"click",OpenLayers.Function.bind(function(){if(this.parallelDrawingControl.active){this.parallelDrawingControl.deactivate();
this.parallelDrawingButton.className="olEditorParallelDrawingInactive"}else{this.parallelDrawingControl.activate();this.parallelDrawingButton.className="olEditorParallelDrawingActive"}},this,this.parallelDrawingButton));b.appendChild(this.parallelDrawingButton);this.guidedDrawingButton=document.createElement("div");this.guidedDrawingButton.title=OpenLayers.i18n("oleCADToolsDialogGuidedDrawing");this.guidedDrawingButton.className=this.fixedAngleDrawingControl.active?"olEditorGuidedDrawingActive":"olEditorGuidedDrawingInactive";
OpenLayers.Event.observe(this.guidedDrawingButton,"click",OpenLayers.Function.bind(function(){if(this.fixedAngleDrawingControl.active){this.fixedAngleDrawingControl.deactivate();this.guidedDrawingButton.className="olEditorGuidedDrawingInactive"}else{this.fixedAngleDrawingControl.activate();this.guidedDrawingButton.className="olEditorGuidedDrawingActive"}},this,this.guidedDrawingButton));b.appendChild(this.guidedDrawingButton);a.appendChild(b);var c=document.createElement("div"),d=document.createElement("p"),
e=document.createElement("input");e.type="checkbox";e.id="oleCADToolsDialogShowLayer";e.name="guidedDrawing";e.value="true";e.checked=true;e.defaultChecked=true;this.setShowGuides(e.checked);d.appendChild(e);OpenLayers.Event.observe(d,"click",OpenLayers.Function.bind(function(f){OpenLayers.Event.stop(f,true);this.setShowGuides(e.checked)},this));b=document.createElement("label");b.htmlFor="oleCADToolsDialogShowLayer";b.appendChild(document.createTextNode(OpenLayers.i18n("oleCADToolsDialogShowLayer")));
d.appendChild(b);c.appendChild(d);d=document.createElement("p");b=document.createElement("input");b.type="text";b.id="oleCADToolsDialogTolerance";b.size=4;b.value=this.tolerance;OpenLayers.Event.observe(b,"change",OpenLayers.Function.bind(function(f){this.setTolerance(f.target.value)},this));d.appendChild(b);b=document.createElement("label");b.htmlFor="oleCADToolsDialogTolerance";b.appendChild(document.createTextNode(OpenLayers.i18n("oleCADToolsDialogTolerance")));d.appendChild(b);c.appendChild(d);
a.appendChild(c);this.map.editor.dialog.show({content:a,toolbox:true})}},setTolerance:function(a){this.tolerance=a;this.snappingControl.setTargets([{layer:this.map.getLayersByClass("OpenLayers.Editor.Layer.Snapping")[0],tolerance:this.tolerance}])},setShowGuides:function(a){this.map.getLayersByClass("OpenLayers.Editor.Layer.Snapping")[0].setVisibility(a)},CLASS_NAME:"OpenLayers.Editor.Control.CADTools"});
OpenLayers.Editor.Control.ParallelDrawing=OpenLayers.Class(OpenLayers.Control,{CLASS_NAME:"OpenLayers.Editor.Control.ParallelDrawing",active:false,guideLine:null,guideLineSegment:null,initialize:function(a){OpenLayers.Control.prototype.initialize.call(this);this.layer=a},activate:function(){var a=OpenLayers.Control.prototype.activate.call(this);a&&this.layer.events.on({pointadded:this.closestSegment,sketchcomplete:this.onSketchComplete,scope:this});return a},deactivate:function(){var a=OpenLayers.Control.prototype.deactivate.call(this);
a&&this.layer.events.un({pointadded:this.closestSegment,sketchcomplete:this.onSketchComplete,scope:this});return a},closestSegment:function(a){var b=null,c=Number.MAX_VALUE;this.layer.features.forEach(function(f){var g=[];if(f.geometry instanceof OpenLayers.Geometry.Curve)g=f.geometry.getSortedSegments();else f.geometry instanceof OpenLayers.Geometry.Polygon&&f.geometry.components.forEach(function(h){h.getSortedSegments().forEach(function(i){g.push(i)})});g.forEach(function(h){if(!(this.guideLineSegment!==
null&&this.guideLineSegment.x1===h.x1&&this.guideLineSegment.y1===h.y1&&this.guideLineSegment.x2===h.x2&&this.guideLineSegment.y2===h.y2)){var i=(new OpenLayers.Geometry.LineString([new OpenLayers.Geometry.Point(h.x1,h.y1),new OpenLayers.Geometry.Point(h.x2,h.y2)])).distanceTo(new OpenLayers.Geometry.Point(a.point.x,a.point.y));if(i<c){c=i;b=h}}},this)},this);if(b){this.guideLineSegment=b;this.removeGuides();var d=this.getSnappingGuideLayer(),e=d.getLine(b);e.b+=a.point.y-(e.m*a.point.x+e.b);this.guideLine=
d.addLine(e)}},getSnappingGuideLayer:function(){return this.map.getLayersByClass("OpenLayers.Editor.Layer.Snapping")[0]},onSketchComplete:function(){this.removeGuides()},removeGuides:function(){this.guideLine!==null&&this.getSnappingGuideLayer().removeFeatures([this.guideLine]);this.guideLine=null}});
